version: "3.9"

services:
  app:
    build: .
    container_name: nodejs
    restart: on-failure
    environment:
      - MONGO_URL=mongodb://db:27017
    links:
      - "db"
    ports:
      - "8000:8000"

  db:
    image: "mongo:4.4.4"
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb: